<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Failed test isnull]]>
    </line>
    <line>
      <![CDATA[<br><img src='C:\Users\asadu\Documents\PNT\screenshoot\1555698991449.jpg'height ='400' width = '400'/><br>]]>
    </line>
    <line>
      <![CDATA[Failed test isnull]]>
    </line>
    <line>
      <![CDATA[<br><img src='C:\Users\asadu\Documents\PNT\screenshoot\1555698994857.jpg'height ='400' width = '400'/><br>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="103860" started-at="2019-04-19T18:34:51Z" finished-at="2019-04-19T18:36:35Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.testRunner@3abbfa04]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="103860" started-at="2019-04-19T18:34:51Z" finished-at="2019-04-19T18:36:35Z">
      <class name="runner.testRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runner.testRunner@3abbfa04]" name="setUpClass" is-config="true" duration-ms="253" started-at="2019-04-19T18:34:51Z" finished-at="2019-04-19T18:34:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runner.testRunner@3abbfa04]" name="feature" duration-ms="96663" started-at="2019-04-19T18:34:52Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-04-19T18:36:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test1]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at stepDefinition.NewTest.home_page_is_open(NewTest.java:34)
at âœ½.Then home page is open(Features.feature:5)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
            <line>
              <![CDATA[Failed test isnull]]>
            </line>
            <line>
              <![CDATA[<br><img src='C:\Users\asadu\Documents\PNT\screenshoot\1555698991449.jpg'height ='400' width = '400'/><br>]]>
            </line>
            <line>
              <![CDATA[Failed test isnull]]>
            </line>
            <line>
              <![CDATA[<br><img src='C:\Users\asadu\Documents\PNT\screenshoot\1555698994857.jpg'height ='400' width = '400'/><br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runner.testRunner@3abbfa04]" name="tearDownClass" is-config="true" duration-ms="674" started-at="2019-04-19T18:36:34Z" finished-at="2019-04-19T18:36:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runner.testRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
